---
- name: Ensure PostgreSQL service is running
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Create DHIS2 database and user
  become_user: postgres
  postgresql_user:
    name: dhis
    password: dhis
    priv: "ALL"

- name: Create DHIS2 database
  become_user: postgres
  postgresql_db:
    name: dhis2
    owner: dhis

- name: Unzip the database dump file
  unarchive:
    src: /mnt/data/dhis2-db-sierra-leone.zip
    dest: /mnt/data/
    remote_src: yes

- name: Restore the DHIS2 database
  become_user: postgres
  command: "psql -U dhis -d dhis2 -f /mnt/data/dhis2-db-sierra-leone.sql"
  args:
    creates: /mnt/data/dhis2-db-sierra-leone.sql
